### ISSUE TITLE
Error when trying to process dumps

### ISSUE THREAD

**Issue by rustiferch** [Team-Resurgent/Repackinator#21]
Hi Team,

I get the below error when trying to process re-dumps. Any idea why? I've checked and can confirm I'm running as an admin.

13:57:23 Error - Exception occured 'System.UnauthorizedAccessException: Access to the path 'D:\System Volume Information' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFileSystemEntries(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFileSystemEntries(String path, String searchPattern, SearchOption searchOption)
   at Repackinator.Actions.Repacker.StartRepacking(GameData[] gameData, Config config, Action`1 progress, Action`1 logger, Stopwatch stopwatch, CancellationToken cancellationToken)'.

**Comment by rustiferch** [comment]
I ended up putting games into a sub folder, but got the below error instead. It looks like some sort of permissions issue but I can confirm I have full control of the folders.

16:16:01 Info - Processing '********.7z'...
16:16:01 Error - Processing 'D:\XBOX\********.7z' caused error 'System.IO.FileNotFoundException: Could not find file 'E:\XBOX\Repackinator-Temp\Repackinator.1.temp'.
File name: 'E:\XBOX\Repackinator-Temp\Repackinator.1.temp'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Resurgent.UtilityBelt.Library.Utilities.ImageInput.XisoInput..ctor(String[] parts)
   at Repackinator.Actions.Repacker.ProcessArchive(String inputFile, String outputPath, GroupingEnum grouping, Boolean hasAllCrcs, Boolean upperCase, Boolean compress, Boolean trimmedScrub, CancellationToken cancellationToken)'.

16:16:01 Done - Completed Processing List (Time Taken 00:00:13).

**Comment by cheezebow** [comment]
> I ended up putting games into a sub folder, but got the below error instead. It looks like some sort of permissions issue but I can confirm I have full control of the folders.
> 
> 16:16:01 Info - Processing '********.7z'... 16:16:01 Error - Processing 'D:\XBOX********.7z' caused error 'System.IO.FileNotFoundException: Could not find file 'E:\XBOX\Repackinator-Temp\Repackinator.1.temp'. File name: 'E:\XBOX\Repackinator-Temp\Repackinator.1.temp' at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at Resurgent.UtilityBelt.Library.Utilities.ImageInput.XisoInput..ctor(String[] parts) at Repackinator.Actions.Repacker.ProcessArchive(String inputFile, String outputPath, GroupingEnum grouping, Boolean hasAllCrcs, Boolean upperCase, Boolean compress, Boolean trimmedScrub, CancellationToken cancellationToken)'.
> 
> 16:16:01 Done - Completed Processing List (Time Taken 00:00:13).

I get exact same problem. 
Tried running as admin etc and nothing works.

**Comment by HoRnEyDvL** [comment]
Can you please share a screenshot of the paths setup in the repackinator screen?

Thanks

**Comment by EqUiNoX-Labs** [comment]
I have updated Repackinator to ignore permission denied when scanning directories it does not have permission to, this should fix your issue and will be v1.2.5. As a work around don't use a root folder as source of your iso's put them into a folder of their own and user that as source.

**Comment by cheezebow** [comment]
![Skärmbild 2023-01-02 185418](https://user-images.githubusercontent.com/51707725/210265694-a6c59efc-28c1-4203-b6de-f2f6433166b3.png)
 looking forward to try 1.2.5

**Comment by rustiferch** [comment]
Here's my screen shot too - 
![Screenshot 2023-01-03 103606](https://user-images.githubusercontent.com/87345649/210285045-5985bd08-40a2-41c9-8fea-ed71a121ea63.png)

**Comment by HoRnEyDvL** [comment]
Hey guys new version is out, can you please give that a shot ?

**Comment by rustiferch** [comment]
Hi! Thanks for the help :)
I've run it again with version 1.2.5 but I still seem to get the same/similar error. Input folder is D:\XBOX and output is another drive, E:\XBOX

19:38:58 Info - Processing '********.7z'...
19:38:58 Error - Processing 'D:\XBOX\********.7z' caused error 'System.IO.FileNotFoundException: Could not find file 'E:\XBOX\Repackinator-Temp\Repackinator.1.temp'.
File name: 'E:\XBOX\Repackinator-Temp\Repackinator.1.temp'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Resurgent.UtilityBelt.Library.Utilities.ImageInput.XisoInput..ctor(String[] parts)
   at Repackinator.Actions.Repacker.ProcessArchive(String inputFile, String outputPath, GroupingEnum grouping, Boolean hasAllCrcs, Boolean upperCase, Boolean compress, Boolean trimmedScrub, CancellationToken cancellationToken)'.

**Comment by rustiferch** [comment]
I ran the process again and kept the E:\XBOX folder open. Repackinator is able to create/delete the 'Repackinator-Temp' folder, so I don't think the issue is related to permissions.

**Comment by HoRnEyDvL** [comment]
Are you able to join the Discord for some real time support / debugging?

**Comment by cheezebow** [comment]
> Hey guys new version is out, can you please give that a shot ?

I tried it and i got same error message about permission.
so of curiosity i fixed some new dump files from other source and it worked, so my .7z dumps must be all bad even if they work on Xbox.
So now im trying to find a way to get working dumps.

**Comment by rustiferch** [comment]
Hmm, maybe I'll try the same.

**Comment by rustiferch** [comment]
> Are you able to join the Discord for some real time support / debugging?

Happy to help with debugging. Only issue is I think I'm in another timezone than you guys. GMT+11.

**Comment by HoRnEyDvL** [comment]
@rustiferch  thats fine someone will be around. Hop on &  let us know :)
