### ISSUE TITLE
1.2.8 Crashes on startup (Win 10, Intel HD3000 GPU)

### ISSUE THREAD

**Issue by tonelab77** [Team-Resurgent/Repackinator#36]
1.2.8 crashes before the gui loads.

SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateVertexShader(IntPtr shaderBytecodeRef, PointerSize bytecodeLength, ClassLinkage classLinkageRef, VertexShader vertexShaderOut)
   at SharpDX.Direct3D11.VertexShader..ctor(Device device, Byte[] shaderBytecode, ClassLinkage linkage)
   at Veldrid.D3D11.D3D11Shader..ctor(Device device, ShaderDescription description)
   at Veldrid.D3D11.D3D11ResourceFactory.CreateShaderCore(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription description)
   at Repackinator.UI.ImGuiController.CreateDeviceResources(GraphicsDevice gd, OutputDescription outputDescription)
   at Repackinator.UI.ImGuiController..ctor(GraphicsDevice gd, OutputDescription outputDescription, Int32 width, Int32 height)
   at Repackinator.UI.ApplicationUI.Run()
   at Repackinator.UI.ApplicationUIStartup.Start(String version)

**Comment by zappepappe** [comment]
Intel HD3000 is not a Direct3D 11 capable GPU.

**Comment by HoRnEyDvL** [comment]
Are you able to try now with latest release?

Thanks

**Comment by HoRnEyDvL** [comment]
Closed due to no response. Please try latest version to confirm if issue is fixed otherwise raise new ticket.

Thanks

**Comment by HoRnEyDvL** [comment]
Closed due to no response. Please try latest version to confirm if issue is fixed otherwise raise new ticket.

Thanks
