### ISSUE TITLE
Repackinator wont load

### ISSUE THREAD

**Issue by DustyBin1980** [Team-Resurgent/Repackinator#40]
When I try and run repackintor as admin it loads up the cmd screen for about a second then another blank white window appears for around 3 seconds and then it crashes.  My crash log is as follows:

SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateVertexShader(IntPtr shaderBytecodeRef, PointerSize bytecodeLength, ClassLinkage classLinkageRef, VertexShader vertexShaderOut)
   at SharpDX.Direct3D11.VertexShader..ctor(Device device, Byte[] shaderBytecode, ClassLinkage linkage)
   at Veldrid.D3D11.D3D11Shader..ctor(Device device, ShaderDescription description)
   at Veldrid.D3D11.D3D11ResourceFactory.CreateShaderCore(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription description)
   at Repackinator.UI.ImGuiController.CreateDeviceResources(GraphicsDevice gd, OutputDescription outputDescription)
   at Repackinator.UI.ImGuiController..ctor(GraphicsDevice gd, OutputDescription outputDescription, Int32 width, Int32 height)
   at Repackinator.UI.ApplicationUI.Run()
   at Repackinator.UI.ApplicationUIStartup.Start(String version)

Im using windows 10 have the pre requisite files installed and I am running direct x 12 any help would be gratefully received

**Comment by Dempsey86** [comment]
What are your pc specs?

**Comment by zappepappe** [comment]
That's the same error I get when I try to run on a GPU that doesn't support D3D11.

**Comment by DustyBin1980** [comment]
@zappepappe  you were spot on mate swapped over to my I3 desktop and its running a treat now thanks for the info man
