### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by zappepappe** [Team-Resurgent/Repackinator#8]
The application instantly crashes on a Windows 10 21H1 machine.

Crashlog-09252022170946:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Veldrid.OpenGL.OpenGLGraphicsDevice.Init(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height, Boolean loadFunctions)
   at Veldrid.OpenGL.OpenGLGraphicsDevice..ctor(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
   at Veldrid.GraphicsDevice.CreateOpenGL(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
   at Veldrid.StartupUtilities.VeldridStartup.CreateDefaultOpenGLGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, GraphicsBackend backend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at RepackinatorUI.Application.Run()
   at Program.<Main>$(String[] args)
```
[Crashlog-09252022170946.txt](https://github.com/Team-Resurgent/Repackinator/files/9641083/Crashlog-09252022170946.txt)

**Comment by Natetronn** [comment]
Are you running Windows in a VM, by chance or is this your main OS?

**Comment by zappepappe** [comment]
As I said, a Windows 10 21H1 machine. No VM.

**Comment by zappepappe** [comment]
With version 1.1 I get:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Veldrid.OpenGLBinding.OpenGLNative.glDebugMessageCallback(DebugProc callback, Void* userParam)
   at Veldrid.OpenGL.OpenGLGraphicsDevice.EnableDebugCallback(DebugProc callback)
   at Veldrid.OpenGL.OpenGLGraphicsDevice.Init(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height, Boolean loadFunctions)
   at Veldrid.OpenGL.OpenGLGraphicsDevice..ctor(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
   at Veldrid.GraphicsDevice.CreateOpenGL(GraphicsDeviceOptions options, OpenGLPlatformInfo platformInfo, UInt32 width, UInt32 height)
   at Veldrid.StartupUtilities.VeldridStartup.CreateDefaultOpenGLGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, GraphicsBackend backend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateWindowAndGraphicsDevice(WindowCreateInfo windowCI, GraphicsDeviceOptions deviceOptions, GraphicsBackend preferredBackend, Sdl2Window& window, GraphicsDevice& gd)
   at RepackinatorUI.Application.Run()
   at Program.<Main>$(String[] args)
```

**Comment by Natetronn** [comment]
I think this issue relates to Veldrid needing OpenGL.

What version of OpenGL do you have on your system? Do you have a Deditcated GPU or an Internal or CPU based one? Maybe updating or installing drivers (or removing and reinstalling) for your particular graphics card will address the issue. You might need to get the drivers direct from the manufacturer; directly from nvidia for example(if you're running a nvidia gpu, that is.)

https://answers.microsoft.com/en-us/windows/forum/all/opengl-drivers/9b52324e-1083-44e1-83f7-ff2e35bf07a2

Veldrid OpenGL support:
https://github.com/mellinoe/veldrid-docs/blob/master/articles/implementation/opengl.md

**Comment by zappepappe** [comment]
It's an older dedicated graphics card with no newer drivers available. According to OpenGL Extension Viewer the system is fully OpenGL 3.3 compatible and mostly 4.2 compatible. As I understand it Veldrid only requires 3.0.

**Comment by Natetronn** [comment]
Thanks for the response and checking on that. I'll forward this to main dev.

**Comment by zappepappe** [comment]
Do you know of any other similar applications using Veldrid to check if this is specific to Repackinator?

**Comment by EqUiNoX-Labs** [comment]
@zappepappe can you DM me on discord, have done a possible fix but would like you to test.

EqUiNoX#6216

**Comment by HoRnEyDvL** [comment]
Ticket Closed, looks like it has been resolved.
