### ISSUE TITLE
I'm getting the below error trying to process some 7Z Backups. Any Ideas?

### ISSUE THREAD

**Issue by rustiferch** [Team-Resurgent/Repackinator#9]
13:11:55 Info - Processing '007 - Agent Under Fire [!].7z'...
13:11:55 Info - Extracting, Removing Video Partition & Splitting ISO...
13:11:55 Error - Processing 'C:\temp\XBOX IN\007 - Agent Under Fire [!].7z' caused error 'System.IO.FileNotFoundException: Could not find file 'C:\temp\XBOX OUT\Repackinator-Temp\Repackinator.1.iso'.
File name: 'C:\temp\XBOX OUT\Repackinator-Temp\Repackinator.1.iso'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Repackinator.Shared.Repacker.ProcessFile(String inputFile, String outputPath, GroupingEnum grouping, Boolean alternate, Boolean hasAllCrcs, CancellationToken cancellationToken)'.

13:11:55 Done - Completed Processing List (Time Taken 00:00:00).

**Comment by Natetronn** [comment]
Perhaps try removing the `[!]` for the name?
